### ISSUE TITLE
Support new networks(LINE / Bluesky / Hatena Bookmark)

### ISSUE THREAD

**Issue by memory-lovers** [stefanobartoletti/nuxt-social-share#132]
Thank you for your great package!!

### Describe your suggestion

I would like to share to below SNS.

- [LINE](https://line.me/)
- [Bluesky](https://bsky.social/about)
- [Hatena Bookmark](https://b.hatena.ne.jp/)

### Use cases

I would like to support new networks.

### Describe alternatives you've considered

I couldn't find any good ideas..

### Additional context

Specifications and Color for each SNS are below.

- LINE
   - `https://line.me/R/share?text=[u]`([ref](https://developers.line.biz/en/docs/line-login/using-line-url-scheme/#sending-text-messages))
   - `#06C755` ([ref](https://creative.line.me/ja/guide/brand-guideline/app-icon-en))
- Bluesky
  - `https://bsky.app/intent/compose?text=[u]` ([ref](https://github.com/bluesky-social/social-app/pull/2587))
  - `#1185FE`
- Hatena Bookmark
  - `https://b.hatena.ne.jp/entry?url=[u]` ([ref](https://b.hatena.ne.jp/guide/bbutton))
  - `#00A4DE` ([ref](https://brand.hatena.co.jp/hatenabookmark#guide-symbolmark))

And, I'm developing this feature a bit.
If you don't mind, can I submit a PR?

- https://github.com/stefanobartoletti/nuxt-social-share/commit/e281b5055a158aa3b46f60af89a29d0ce0c518d1

P.S.
I'm not good at English, and this is my first issue.
Forgive me if I make you feel bad by using incorrect words in English, i don't mean it at all.

**Comment by stefanobartoletti** [comment]
Hi @memory-lovers, thanks for this, and first of all no worries, your english is very good and the message was clear and polite :)

I had a look at your proposed PR, and it looks good to me, but there are some notes before submitting it:

- I would prefer to have a dedicated PR for each proposed service instead of a catch-all. That way, if some edits or fixing will be required, it will be easier to review and to keep everything in scope.

About the proposed networks:
- Including Line is ok, as it is a widespread messaging app. I'm not using it personally, so I need to ask you to double-check if the URL is working as expected. Then you can proceed with a dedicated PR.
- About Bluesky, I never heard about it before, but judging from the app in the Play Store, it seems to be quite popular.  Even here, please check if the share URL is working before opening a PR.
- For Hatena, I am not sure if it is a good fit for inclusion at this moment. Is far as I can see, the linked site is only in Japanese (If I am not wrong) and I cannot find some reference in English. I am a bit reluctant to include code where I cannot personally read documentation, even for something as trivial as a share URL: in this context, it will be very hard for me to ensure future maintainability should the API change or if issues arise that need to be addressed. Also, judging by their social accounts, it seems that it is not as widespread as other services included in this module. I'm sorry, but for this specific service at the moment I should reject the inclusion.

Please note that I was also thinking about including a way to use a customized network, but a the moment it is just an idea. If implemented, I will work on it no sooner than Nuxt 4 will be released. But maybe that could cover your specific need.


Anyway, thanks for this valuable contribution, I really appreciated that you also included links to the apps' docs for reference!

**Comment by memory-lovers** [comment]
Hi @stefanobartoletti , thank you for your comment!
It's just that Google Translate is a very good product :)

> I would prefer to have a dedicated PR for each proposed service instead of a catch-all.

OK, I will try to create a PR for each feature.

**LINE**

- I have confirmed that it works correctly on mobile.
- Due to the specifications of LINE, it does not work on a desktop PC.

**Bluesky**

- Bluesky is a service expected to be alternative Twitter.
- I have confirmed that it works correctly on mobile and desktop PC.

**Hatena Bookmark**

- Sorry, this is a feature unique to Japan.
- It is a Japanese social bookmarking service.
- In Japan, a website can attract the attention of many people by being shared there.
- I also need it because it is always used by famous blog sites in Japan ([Zenn](https://zenn.dev/) / [Qiita](https://qiita.com/)).
- Of course, I understand that this is a uniquely Japanese culture.
- And I understand why it was rejected. No worries.

> Please note that I was also thinking about including a way to use a customized network, 

That's a great feature! I'm looking forward to it :)

And, thank you for your polite and clear comment!

**Comment by stefanobartoletti** [comment]
@memory-lovers your contributions have been merged, and available in the latest release
